### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by mossmoss** [anurodhp/Monal#134]
I'm running iPhone iOS 12.1 and Monal 3.1 (297) -- apparently it was released yesterday. 

I tried to login and updated my expired password and could no longer login. For a while I was getting a not authorized red bar at top, maybe bad password? The slider color would be green on enabling account but upon saving and rechecking, the right side dot is always red. 

Running against OpenFire / Jive 4.2.3. 

Strangely, I think I saw the JID logged-in from my iPhone & Monal in the Jive console, though the device / client showed no contacts and a red dot. 

I'm using a custom server address and TLS. I tried the auto setup with the same result. 

Does auto setup consult DNS for XMPP server?

Thanks!

**Comment by anurodhp** [comment]
it does, the welcome screen setup is the same as the other one it just hides a lot of the external fields. That said, I think I know what is wrong. There is an annoying bug I am fixing where if you change your password an internal cache doesn't update right and you run into a failed login loop. Could you try swiping up to force close the app and then restart it? That should resolve it.  Fixing that bug is a high priority.

**Comment by mossmoss** [comment]
I tapped home key twice and swiped up to close Monal, unfortunately after restarting, it did not resolve, I also tried restarting the phone but no help. Additionally, I have deleted and re-downloaded the app several times. Also, the quick setup seems just to use the domain for Account@something.com (I can see this when examining the settings after setup) ... our XMPP server is specified in the special DNS records, and I don't see that it is selected as the server, so I'm not sure this is working as expected.

**Comment by anurodhp** [comment]
crashlytics should only be for crashes.  Monal takes the domain part of the jid and does do a dns lookup to see where it should login, it does this on both the manual and automatic entries. login error bugs are odd and are usually the result of a misc configuration somewhere.  I really need to improve the error logging (like an error history screen) to make the debugging process easier. 
In the short term,   if any of these are public servers could you send it to info@monal.im? If its your own server, an temp test account would be even better, if I can replicate the issue I can put out a patch in a few days.

**Comment by anurodhp** [comment]
The most recent beta should correctly look at your DNS records. Could you let me know how it works for you:
https://testflight.apple.com/join/RjIlyvqa

**Comment by benjaminbischoff** [comment]
@anurodhp 
Yes, now it works :). Just tested few minutes ago ;).
Thx!
